// ──────────────────────────────────────────────
// Toolreport Designer — API Layer Types
// ──────────────────────────────────────────────

import type { DiscoveredField, TemplateVarVisibility } from '@/types/designer'

/** Normalized API error */
export interface ApiError {
    status: number
    message: string
    /** Validation errors keyed by field, if present */
    errors?: Record<string, string[]>
}

/** Configuration for ApiClient */
export interface ApiConfig {
    baseURL: string
    authToken?: string
    timeout?: number
}

/** Query parameters for paginated list endpoints */
export interface QueryParams {
    page?: number
    per_page?: number
    sort?: 'name' | 'slug' | 'created_at' | 'updated_at'
    order?: 'asc' | 'desc'
    search?: string
}

/** Paginated API response wrapper */
export interface PaginatedResponse<T> {
    data: T[]
    meta: {
        current_page: number
        last_page: number
        per_page: number
        total: number
    }
}

/** PdfTemplate resource from API */
export interface PdfTemplate {
    id: number
    name: string
    slug: string
    description: string | null
    page: Record<string, unknown>
    config: Record<string, unknown>
    is_active: boolean
    engine?: 'dompdf' | 'pdf-engine'
    element_count: number
    created_at: string
    updated_at: string
}

/** PdfDocument resource from API */
export interface PdfDocument {
    id: number
    template_id: number
    title: string
    status: 'pending' | 'generating' | 'done' | 'failed'
    file_size: number | null
    is_downloadable: boolean
    generated_at: string | null
    created_at: string
    updated_at: string
}

/** Payload for creating a template */
export interface CreateTemplatePayload {
    name: string
    slug: string
    description?: string | null
    page: Record<string, unknown>
    config: Record<string, unknown>
    is_active?: boolean
    engine?: 'dompdf' | 'pdf-engine'
}

/** Payload for updating a template (partial) */
export type UpdateTemplatePayload = Partial<CreateTemplatePayload>

/** Payload for generating a PDF */
export interface GeneratePayload {
    title: string
    data: Record<string, unknown>
}

/** Request payload for testing a datasource connection */
export interface DatasourceTestRequest {
    datasource: {
        /** Unique ID generated by the frontend — links back to DatasourceConfig */
        id: string
        url: string
        method: 'GET' | 'POST'
        headers?: Record<string, string>
        auth?: { type: 'none' | 'bearer'; token?: string }
        timeout?: number
    }
}

/** Result of a datasource test call */
export interface DatasourceTestResult {
    success: boolean
    fields?: DiscoveredField[]
    error?: string
    status: number
}

// ── Template Variables ──────────────────────

/** TemplateVar resource from API */
export interface TemplateVar {
    id: number
    pdf_template_id: number
    name: string
    /** Value masked as `***` for private vars in API responses */
    value: string | null
    visibility: TemplateVarVisibility
    is_required: boolean
    description: string | null
    created_at: string
    updated_at: string
}

/** Payload for creating a template var */
export interface CreateTemplateVarPayload {
    name: string
    value?: string | null
    visibility: TemplateVarVisibility
    is_required?: boolean
    description?: string | null
}

/** Payload for updating a template var (partial) */
export type UpdateTemplateVarPayload = Partial<CreateTemplateVarPayload>

/** Full API client interface */
export interface ApiClient {
    getTemplates(params?: QueryParams): Promise<PaginatedResponse<PdfTemplate>>
    getTemplate(id: number): Promise<PdfTemplate>
    createTemplate(data: CreateTemplatePayload): Promise<PdfTemplate>
    updateTemplate(id: number, data: UpdateTemplatePayload): Promise<PdfTemplate>
    deleteTemplate(id: number): Promise<void>

    generatePdf(templateId: number, data: GeneratePayload): Promise<PdfDocument>
    getDocuments(templateId: number): Promise<PdfDocument[]>
    getDownloadUrl(documentId: number): string

    testDatasource(templateId: number, request: DatasourceTestRequest): Promise<DatasourceTestResult>

    // ── Template Variables ──────────────────────
    getTemplateVars(templateId: number): Promise<TemplateVar[]>
    createTemplateVar(templateId: number, data: CreateTemplateVarPayload): Promise<TemplateVar>
    updateTemplateVar(templateId: number, templateVarId: number, data: UpdateTemplateVarPayload): Promise<TemplateVar>
    deleteTemplateVar(templateId: number, templateVarId: number): Promise<void>
}
